/**
 * Arize cloud tracing init (plan issue C).
 *
 * Run the `arize-instrumentation` skill to generate the real OpenInference /
 * OpenTelemetry setup for the @anthropic-ai/sdk. This stub is the single place
 * that wiring should live; it must run BEFORE the Anthropic client is created
 * (see index.ts ordering) so instrumentation can patch the SDK.
 *
 * Demo-critical reminder: the "tokens before/after compression" visual is NOT
 * automatic. Emit it as custom span attributes around the Claude calls, and
 * verify the Token Company wrapper doesn't hide calls from auto-instrumentation.
 */
export async function initArize(): Promise<void> {
  const spaceId = process.env.ARIZE_SPACE_ID;
  const apiKey = process.env.ARIZE_API_KEY;
  if (!spaceId || !apiKey) {
    console.warn("[arize] ARIZE_SPACE_ID / ARIZE_API_KEY not set — tracing disabled");
    return;
  }
  // TODO: register OTel tracer provider + OpenInference Anthropic instrumentation
  // (generated by the arize-instrumentation skill).
  console.log("[arize] tracing init placeholder — run arize-instrumentation skill");
}
